title: "Goeun Kim"
description: "AI & Robotics Research Blog"

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

mathjax: true

theme: minima

permalink: /:categories/:year/:month/:day/:title.html

collections:
  projects:
    output: true
